name: proyecto_cobros
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+21

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+1
  flutter_modular: ^2.0.1
  bubble_bottom_bar: ^1.2.0
  shared_preferences: ^0.5.6+3
  edge_alert: ^0.0.1
  flutter_signature_view: ^1.1.1
  shimmer: ^1.1.0
  intl: ^0.16.1
  fl_chart: ^0.8.7
  percent_indicator: "^2.1.1"
  onesignal_flutter: ^2.3.4
  simple_animations: ^1.3.11
  local_auth: ^0.6.1+3
  flutter_secure_storage: ^3.3.2
  get: ^3.4.6
  flutter_plugin_android_lifecycle: 1.0.3
  image_picker: 0.6.2+3
  flutter_slidable: "^0.5.4"
  progress_dialog: ^1.2.2
  advance_pdf_viewer: 1.1.6
  pdf: ^1.8.0
  image: ^2.1.12
  convert: ^2.1.1
  share_extend: "^1.1.5"
  flutter_datetime_picker: ^1.3.8
  google_fonts: ^1.1.0
  overlay_support: ^1.0.5
  connectivity: ^0.4.9
  font_awesome_flutter: ^8.8.1
  timeline_tile: ^1.0.0
  country_icons: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/home/trazabilidad.png
    - assets/cobros/telefone.png
    - assets/cobros/zap.png
    - assets/cobros/paraguaycircle.png
    # - assets/icons/assinatura.png
    # - assets/icons/icon.jpg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
